### ISSUE TITLE
Help Library Usage 

### ISSUE THREAD

**Issue by Suryeah** [twrackers/Calculus-library#6]
Hi Thomas,
      I appreciate your work on Calculus Library which is really amazing. I need some help in using this library on my project. 

Requirement: 
I am using a Function Generator to produce Sine wave of 1Hz.
This is feed to 10Bit SAR ADC in ESP32. 
Theoratically - when sin wave is integrated it gives Cos wave [Phase Shift by 90Deg] with reduced amplitude.  

Could you please help me in getting my code work as per my requirement.!

Thank you in Advance . ! 

`#include <Cache.h>
#include <Integrator.h>
#include <Quadratic.h>
#include <TimeStep.h>

const int analogInPin = A0;
int sensorValue = 0;  

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
}

void loop() {
  // put your main code here, to run repeatedly:
  sensorValue = analogRead(analogInPin);
  Serial.print(sensorValue);
  Serial.print("   ");
  Integrator inte = Integrator(0.001207);
  Serial.println(inte.step(sensorValue));
}`

**Comment by twrackers** [comment]
Hi, thanks for your feedback.  Sorry it took me a few days to get back to
you.

First, you don't want to call the Integrator constructor within the loop()
function, you will quickly exhaust available memory because a new
Integrator object will be created each time through. Also, you need to
change how the constructor is called.  It takes a TimeStep object as its
argument.  Here's what I think you want to start with.

#include <Integrator.h>
#include <TimeStep.h>

const int analogInPin = A0;
// Next line doesn't need to be global.
// int sensorValue = 0;

TimeStep ts(0.001207);   // Where does this value come from?

// Define your Integrator here so it holds its internal state between
// passes through loop().
Integrator integ(ts);    // Create integrator with this time step.

void setup {
    Serial.begin(115200);
}

void loop() {
    int sensorValue = analogRead(analogInPin);  // only returns values >= 0
    Serial.print(sensorValue);
    Serial.print(" ");
    double integValue = integ.step((double) sensorValue);
    Serial.println(integValue);
}

Two comments related to the mathematics going on here.

   1. The integral of sin(x) is -cos(x), or a sine wave phase-shifted
   1/4 cycle later.  The integral of cos(x) is sin(x).  Since they're all sine
   waves, they really only differ in phase.
   2. Since the Calculus library is doing a numerical integration, there
   will be some error accumulated over time.  This is especially true of
   integration, where any DC bias of the input signal will cause the outputs
   of the Integrator to drift.  Come to think of it, this will happen anyway
   because the analogRead() can ONLY return positive values.

Where I use integrators is with values which are not measured but are
computed.  This includes rotation encoders where counting backwards, even
to negative values, is perfectly reasonable.

I hope all this is helpful.  Feel free to contact me with any other
questions you may have.  I'll try to minimize my response time.

TWR

Thomas W Rackers
